### ISSUE TITLE
Building release not working?

### ISSUE THREAD

**Issue by jjzieve** [TileDB-Inc/TileDB-Docker#27]
I tried running `docker build -t tiledb:release release` and got the following `make` error:
```
[ 69%] Performing configure step for 'ep_zstd'
CMake Error at ep_tbb-stamp/ep_tbb-download-Release.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/tiledb/TileDB-1.5.1/build/externals/src/ep_tbb-stamp/ep_tbb-download-Release-impl.cmake'

  See also

    /home/tiledb/TileDB-1.5.1/build/externals/src/ep_tbb-stamp/ep_tbb-download-*.log


make[2]: *** [externals/src/ep_tbb-stamp/ep_tbb-download] Error 1
make[1]: *** [CMakeFiles/ep_tbb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Any idea what might be going wrong?

**Comment by ihnorton** [comment]
I just ran that command twice, successfully -- once on linux, and once on macOS. There are several dependencies which are pulled in from network locations, so my first guess is that this is the result of a failed source download.

(if you want to run the latest release w/out modification, then `docker pull tiledb/tiledb:1.5.1` and  `docker run -ti tiledb/tiledb:1.5.1 ...` will pull the image from dockerhub, which does not require building from source)

**Comment by jjzieve** [comment]
Yeah I'm able to pull the docker image, was attempting to build with the S3 enablement. But the network root cause that makes sense, sometime my org has issues with certs... Let me try to confirm this later tonight when I'm in another location.

**Comment by ihnorton** [comment]
In case it helps, I just tagged an image with S3 enabled on Dockerhub: `tiledb/tiledb:1.5.1-s3` (see PR in #28 -- we will include at least S3 for the next release).

**Comment by jjzieve** [comment]
Yup confirmed it was a network problem, was able to build in a different environment. Thanks @ihnorton!
